"""Initial database schema

Revision ID: 3fa39f46d607
Revises: 
Create Date: 2026-05-23 10:32:39.609867
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3fa39f46d607'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packaged_food',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('nutrition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('unpackaged_food',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('foodkeeper_id', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fridge_days_min', sa.Integer(), nullable=True),
    sa.Column('fridge_days_max', sa.Integer(), nullable=True),
    sa.Column('freezer_days_min', sa.Integer(), nullable=True),
    sa.Column('freezer_days_max', sa.Integer(), nullable=True),
    sa.Column('pantry_days_min', sa.Integer(), nullable=True),
    sa.Column('pantry_days_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('added_by_member_id', sa.Integer(), nullable=False),
    sa.Column('packaged_food_id', sa.Integer(), nullable=True),
    sa.Column('unpackaged_food_id', sa.Integer(), nullable=True),
    sa.Column('storage_location', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(packaged_food_id IS NOT NULL AND unpackaged_food_id IS NULL) OR (packaged_food_id IS NULL AND unpackaged_food_id IS NOT NULL)', name='ck_food_inventory_type'),
    sa.ForeignKeyConstraint(['added_by_member_id'], ['household_member.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['packaged_food_id'], ['packaged_food.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unpackaged_food_id'], ['unpackaged_food.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('date_occurred', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['food_inventory.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['household_member.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_ownership',
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('tagged_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['food_inventory.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['household_member.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inventory_item_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_ownership')
    op.drop_table('food_event')
    op.drop_table('food_inventory')
    op.drop_table('household_member')
    op.drop_table('unpackaged_food')
    op.drop_table('packaged_food')
    op.drop_table('household')
    # ### end Alembic commands ###
