import {
  Apple01Icon,
  Baby01Icon,
  BeanIcon,
  BirdIcon,
  BiscuitIcon,
  Bread01Icon,
  Bread04Icon,
  CarrotIcon,
  ChickenThighsIcon,
  Coffee02Icon,
  CrabIcon,
  DrumstickIcon,
  EggsIcon,
  FishIcon,
  Hamburger02Icon,
  Honey01Icon,
  JarIcon,
  PieIcon,
  PiggyBankIcon,
  PrawnIcon,
  SnowIcon,
  SpoonAndForkIcon,
  SteakIcon,
  WheatIcon,
} from '@hugeicons/core-free-icons';

const categoryIcons = {
  'Baby Food': Baby01Icon,
  'Baked Goods (Bakery)': Bread04Icon,
  'Baked Goods (Baking and Cooking)': BiscuitIcon,
  'Baked Goods (Refrigerated Dough)': Bread01Icon,
  Beverages: Coffee02Icon,
  'Condiments, Sauces & Canned Goods': JarIcon,
  'Dairy Products & Eggs': EggsIcon,
  'Food Purchased Frozen': SnowIcon,
  'Grains, Beans & Pasta': WheatIcon,
  'Meat (Fresh)': PiggyBankIcon,
  'Meat (Shelf Stable Foods)': SteakIcon,
  'Meat (Smoked or Processed)': SteakIcon,
  'Meat (Stuffed or Assembled)': PieIcon,
  'Poultry (Cooked or Processed)': ChickenThighsIcon,
  'Poultry (Fresh)': BirdIcon,
  'Poultry (Shelf Stable Foods)': DrumstickIcon,
  'Poultry (Stuffed or Assembled)': ChickenThighsIcon,
  'Produce (Fresh Fruits)': Apple01Icon,
  'Produce (Fresh Vegetables)': CarrotIcon,
  'Seafood (Fresh)': FishIcon,
  'Seafood (Shellfish)': CrabIcon,
  'Seafood (Smoked)': PrawnIcon,
  'Shelf Stable Foods': Honey01Icon,
  'Vegetarian Proteins': BeanIcon,
  'Deli & Prepared Foods': Hamburger02Icon,
};

export const categoryIcon = (category) => {
  if (!category) return SpoonAndForkIcon;
  return categoryIcons[category] ?? SpoonAndForkIcon;
};
